### ISSUE TITLE
Unclear about the conditions to pass "Database reads" task

### ISSUE THREAD

**Issue by vault123** [php-school/discussions#4]
It seems like I meet the criteria of passing but still I fail.
The display is correct and in the end I run the update. I have checked if the row is being updated and in fact it is.

<img width="1280" alt="screen shot 2018-02-28 at 11 11 00" src="https://user-images.githubusercontent.com/12476828/36782472-6326bcbc-1c79-11e8-9fe1-6917d35b3900.png">

<img width="1052" alt="screen shot 2018-02-28 at 11 10 28" src="https://user-images.githubusercontent.com/12476828/36782460-5a3ed6c0-1c79-11e8-8d61-67f24c2aa739.png">

**Comment by AydinHassan** [comment]
hi @vault123 could you maybe supply PHP / OS version and info please? I will take a look locally to see if I can reproduce.

**Comment by AydinHassan** [comment]
Maybe you could also post your code solution please :)

**Comment by vault123** [comment]
my PHP version is 7.1.7
os - macOS HighSierra 10.13.3

my solution:
```PHP
$pdo = new PDO($argv[1]);

foreach ($pdo->query("SELECT * FROM users WHERE age > 30")->fetchAll() as $result) {
    echo sprintf("User: %s Age: %s Sex: %s \n",$result['name'], $result['age'], $result['gender']);
};

$sql = "UPDATE users SET name = :name_to_set WHERE name = :name_provided";

$result = $pdo
    ->prepare($sql)
    ->execute([':name_to_set' => 'David Attenborough', ':name_provided' => $argv[2]]);
```

**Comment by AydinHassan** [comment]
hey @vault123 - the problem is just because you output an extra space after the user sex `%s \n`. You should be able to see from the results that the actual database verification passed (as it did when I tested your solution - it was just complaining that the output was not exactly correct!

Hope this helps :)

**Comment by vault123** [comment]
hey @AydinHassan. Indeed that was the issue. It passes without the extra space. Thank you for the feedback.

**Comment by AydinHassan** [comment]
no problem - It would be cool if we ignore these sorts of false-positives, but I think it would be a lot of complicated code to do that, maybe not worth it, I'm not so sure.
